from submodules.displays import Waveshare3In7EinkDisplay, IMAGE_TYPE, COLOUR_PROFILE

DISPLAY_CLASS = Waveshare3In7EinkDisplay
DISPLAY_MAX_UPDATE_SPEED_MS = 60000
DISPLAY_HARD_REFRESH_INTERVAL = 10

IMAGE_FORMAT = IMAGE_TYPE.BMP_RAW
COLOUR_PROFILE_TO_USE = COLOUR_PROFILE.ONE_BIT
IMAGE_WIDTH = 280
IMAGE_HEIGHT = 480
IMAGE_ROTATION = 90
